### ISSUE TITLE
Vilka flikar ska vi ha

### ISSUE THREAD

**Issue by SaraGurra** [SaraGurra/IKFFTestRepository#1]
Just nu finns Home, Diplomatik Transcription, Reading Text, Top Layer och About 

Vilka vill vi ha? (About har jag laft till).

**Comment by linneapalm** [comment]
Vilka flikar behöver vi:
Framsida (foto)
Baksida (foto)
Transkibering (av text på baksida)
Information (om hela sidan, kongressen mm)

**Comment by QueenUWE** [comment]
Ev en landningssida också. Om vi inte vill ha Om projektet som den första sidan man kommer till.

**Comment by SaraGurra** [comment]
Förstasidan/landningnssidan är index.html, alltså fliken "hem". Det är den man kommer till om man skriver in adressen saragurra.github.io/IKFFTestRepository/
